web/settings/audio: disable bitrate section when not applicable
imputnet/cobalt pull request #802
Opened 2024-10-04 08:49 UTC by halozat

please delete my closed pr thanks :3

if the audio format is either `best` or `wav`,
the bitrate selector should be greyed out, 
cause it's lossless, or not necessarily re-encoded.
![format: best (not re-encoded)](https://github.com/user-attachments/assets/9ca6ca02-3249-4a78-831d-3d27d75ef93d)
![format: wav (lossless)](https://github.com/user-attachments/assets/6a688eea-0a75-40b1-a616-cc5ff7f01722)
![format mp3 (lossy)](https://github.com/user-attachments/assets/76bc53ba-b502-4ae7-90c3-10dbad703f0b)

2024-10-04 12:07 UTC, wukko requested changes

2024-10-04 12:07 UTC, wukko commented on web/i18n/en/settings.json
why

2024-10-04 12:08 UTC, wukko commented on web/i18n/en/settings.json
we're a 4 space community

2024-10-04 12:15 UTC, halozat commented on web/i18n/en/settings.json
oh shit sorry my prettier was left on by accident. 😭

2024-10-04 12:21 UTC, halozat commented on web/i18n/en/settings.json
i had made a prettier config that is 98% accurate to the cobalt codebase btw.
that 2% is made up of unconsistency, line wrapping

2024-10-04 12:27 UTC, wukko requested changes

2024-10-04 12:27 UTC, wukko commented on web/src/routes/settings/audio/+page.svelte
> +    import settings from "$lib/state/settings";
this import should be on very top, before translations

2024-10-04 13:26 UTC, wukko requested changes

2024-10-04 13:26 UTC, wukko commented on web/i18n/en/settings.json
> +    "audio.bitrate.description": "bitrate only applies to audio conversion into lossy audio formats. cobalt can't improve the source audio quality, so choosing a bitrate over 128kbps may inflate the
bitrate is applied only when converting audio to a lossy format.

2024-10-04 14:13 UTC, wukko requested changes

2024-10-04 14:13 UTC, wukko commented on web/i18n/en/settings.json
> +    "audio.bitrate.description": "bitrate is only applied upon converting audio to a lossy format. cobalt can't improve the source audio quality, so choosing a bitrate over 128kbps may inflate the fi
"bitrate is **applied only** upon converting..."

2024-10-05 15:31 UTC, wukko commented on web/i18n/en/settings.json
> +    "audio.bitrate.description": "bitrate is applied only upon converting audio to a lossy format. cobalt can't improve the source audio quality, so choosing a bitrate over 128kbps may inflate the fi
bitrate is applied only **_when_** converting...

2024-10-05 15:38 UTC, wukko approved these changes

2024-10-05 15:40 UTC, merged